### ISSUE TITLE
boxer bluetooth

### ISSUE THREAD

**Issue by GarryBu** [pfeerick/lang-firmwares#3]
Flashed the firmware boxer-bluetooth-lang-v2.8.4.zip to your Radiomaster... The transmitter is working, but the Bluetooth itself has not appeared anywhere in the menu... The HC08 module is connected to the port, it works, but it does not work in any way...

**Comment by pfeerick** [comment]
I'm actually not sure why I included the boxer in the bluetooth builds - I don't think it currently works on non-frsky B&W radios anyway at present (but will in 2.9 thanks to EdgeTX/edgetx#3607), but even then, only for Frsky bluetooth trainer - you can't use a generic bluetooth module, but something that is compatiable with the frsky bluetooth code, so either their own bluetooth module, or something like https://github.com/dlktdr/BTWifiModule
