### ISSUE TITLE
Missing new Hebrew language in ver 2.9.0 

### ISSUE THREAD

**Issue by mshonak** [pfeerick/lang-firmwares#5]
Hi 
Hebrew language was just release for ver 2.9.0 
can you compile EdgeTx 2.9.0 with hebrew language for us ( for TX with color LCD ). 

"Support for Hebrew was added to radio firmware for color LCD radios and a voice pack is also available."

Thanks

**Comment by pfeerick** [comment]
Thanks for the reminder to add HE to the list... it will be available when the language builds are released.

**Comment by mshonak** [comment]
Thanks  :-)  :-)  👍
