### ISSUE TITLE
Missing Hebrew language  in the new Unofficial builds  2.10

### ISSUE THREAD

**Issue by mshonak** [pfeerick/lang-firmwares#7]
Missing Hebrew language  in the new Unofficial builds  2.10  - Thanks

**Comment by pfeerick** [comment]
There is a bug in the HE translation that will be fixed for 2.10.1... firmware does not compile for some radios, and bootloader translations are invalid for others.

**Comment by mshonak** [comment]
OK , I update to 2.10 with hebrew language using the Cloud Build option and it worked fine - but same time I need the firmware file and in this way it didn't make any file .

**Comment by mshonak** [comment]
Can you made option in the Cloud Build to save the firmware file into my computer instead of burning it on the device directly
Thanks

**Comment by pfeerick** [comment]
That is planned feature, yes. As well as it being available through Companion.

**Comment by pfeerick** [comment]
> OK , I update to 2.10 with hebrew language using the Cloud Build option and it worked fine - but same time I need the firmware file and in this way it didn't make any file . 

Depending on the radio - you never said which - it will compile, but the bootloader will still have invalid text as it should be ASCII only.

**Comment by mshonak** [comment]
The problem with the bootloder was from the beginning when the Hebrew language came out, reported by some friends, so the solution was to update the bootloader if necessary from the English version and then burn the Hebrew language.
I have radiomaster TX16s remote .

**Comment by pfeerick** [comment]
I suspected as much, didn't notice it at the time Hebrew was added. But did when I saw the PL18 firmware failed to build, so have a PR which will probably be merged tomorrow for 2.11, and will be in 2.10.1 also.

**Comment by pfeerick** [comment]
Should be fixed by 69803b4 as since 2.10.1 is being released shortly.
